//! Build the regression corpus for [`girsa_hebrew`] out of the real seforim.
//!
//! ```sh
//! cargo run -p girsa-hebrew --example harvest -- \
//!     "C:/Users/Administrator/Downloads/otzaria_latest/אוצריא" \
//!     crates/girsa-hebrew/fixtures/corpus-regression.tsv
//! ```
//!
//! # Why it harvests pairs instead of answers
//!
//! A fixture of `input → what the normalizer currently returns` is not a test.
//! It passes on the day it is generated and keeps passing through any bug that
//! is introduced consistently, because the expected answer came from the thing
//! under test.
//!
//! So this harvests **evidence** rather than answers: two strings that genuinely
//! occur in the seforim and are genuinely the same word — `וּבַשַּׁבָּת` from Berakhot
//! and `ובשבת` from a sefer with no nikud at all; `שו״ע` from one file and
//! `שו"ע` from another. What each row asserts is that the normalizer brings the
//! two together. Nothing here is invented and nothing is copied from a
//! dictionary.
//!
//! To keep it honest, this file does **not** call `girsa_hebrew`. It groups
//! words with its own three-line key — Hebrew letters, final forms folded — so
//! that a regression in the crate cannot quietly rewrite the fixture to match
//! itself.

use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::fs;
use std::path::{Path, PathBuf};

/// Enough seforim to span the shelves without reading 3.4 GB.
const MAX_FILES: usize = 400;
/// Enough of each sefer to see its habits. Nikud and abbreviation style are
/// consistent within a work, so the first stretch is representative.
const MAX_BYTES_PER_FILE: usize = 400_000;
/// A word seen fewer times than this is more likely grime than vocabulary.
const MIN_OCCURRENCES: usize = 4;
/// Rows per kind. Four kinds well past the 200 rows W2 asks for.
const MAX_ROWS_PER_KIND: usize = 80;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut args = std::env::args().skip(1);
    let (Some(root), Some(out)) = (args.next(), args.next()) else {
        eprintln!("usage: harvest <otzaria-text-root> <output.tsv>");
        std::process::exit(2);
    };

    let files = collect_files(Path::new(&root))?;
    // Stride rather than take: the paths sort by shelf, so the first 400 would
    // all be halacha and the fixture would only know one kind of sefer. Nikud
    // and abbreviation habits vary by shelf, which is the whole point.
    let stride = (files.len() / MAX_FILES).max(1);
    let sample: Vec<&PathBuf> = files.iter().step_by(stride).take(MAX_FILES).collect();
    eprintln!("reading {} of {} seforim", sample.len(), files.len());

    let mut vocab: Vocabulary = Vocabulary::default();
    for path in sample {
        let Ok(bytes) = fs::read(path) else { continue };
        let text = String::from_utf8_lossy(&bytes[..bytes.len().min(MAX_BYTES_PER_FILE)]);
        let name = path
            .file_stem()
            .map_or_else(|| "?".to_string(), |s| s.to_string_lossy().to_string());
        vocab.ingest(&text, &name);
    }
    eprintln!("{} distinct skeletons", vocab.by_skeleton.len());

    let mut rows: Vec<Row> = Vec::new();
    rows.extend(vocab.mark_pairs());
    rows.extend(vocab.quote_mark_pairs());
    rows.extend(vocab.prefix_pairs());
    rows.extend(vocab.ktiv_pairs());
    rows.extend(vocab.attested_abbreviations());

    // A duplicated row inflates the fixture's size without adding a case, which
    // makes "320 rows" a claim about the wrong thing.
    let mut seen: BTreeSet<(&str, String, String)> = BTreeSet::new();
    rows.retain(|r| seen.insert((r.kind, r.left.clone(), r.right.clone())));

    let mut tsv = String::new();
    tsv.push_str(
        "# girsa-hebrew regression corpus. GENERATED by examples/harvest.rs from the\n\
         # Otzaria text tree; every left and right value is a string that genuinely\n\
         # occurs in a sefer. Do not hand-edit — regenerate.\n\
         #\n\
         # kind\tleft\tright\twhere-left\twhere-right\n",
    );
    for row in &rows {
        tsv.push_str(&format!(
            "{}\t{}\t{}\t{}\t{}\n",
            row.kind, row.left, row.right, row.left_from, row.right_from
        ));
    }
    fs::write(&out, tsv)?;

    let mut per_kind: BTreeMap<&str, usize> = BTreeMap::new();
    for row in &rows {
        *per_kind.entry(row.kind).or_default() += 1;
    }
    eprintln!("wrote {} rows to {out}", rows.len());
    for (kind, n) in per_kind {
        eprintln!("  {kind:<10} {n}");
    }
    Ok(())
}

struct Row {
    kind: &'static str,
    left: String,
    right: String,
    left_from: String,
    right_from: String,
}

/// Every surface form seen, grouped by consonant skeleton.
#[derive(Default)]
struct Vocabulary {
    /// skeleton → surface form → (times seen, one sefer it was seen in)
    by_skeleton: HashMap<String, BTreeMap<String, (usize, String)>>,
}

impl Vocabulary {
    fn ingest(&mut self, text: &str, sefer: &str) {
        for raw in text.split(|c: char| c.is_whitespace()) {
            let word = trim_edges(raw);
            if word.is_empty() || word.chars().count() > 14 {
                continue;
            }
            // Otzaria's text carries inline HTML, and a footnote marker like
            // `<i class="footnote" data-n="1">` splits on whitespace into
            // fragments that end in Hebrew: `1"></i>בשתי`. Those are markup,
            // not words, and a fixture row built from one asserts nothing.
            if !word
                .chars()
                .all(|c| is_letter(c) || is_mark(c) || is_quote_mark(c))
            {
                continue;
            }
            // No Hebrew word begins with a vowel point. A token that does is a
            // fragment of one — the corpus has these (BUILDER.md T8) and they
            // are not evidence of anything.
            if word.chars().next().is_some_and(is_mark) {
                continue;
            }
            let skeleton = skeleton_of(word);
            // Two letters is not enough to tell anything apart.
            if skeleton.chars().count() < 3 {
                continue;
            }
            let entry = self
                .by_skeleton
                .entry(skeleton)
                .or_default()
                .entry(word.to_string())
                .or_insert((0, sefer.to_string()));
            entry.0 += 1;
        }
    }

    fn frequent(&self) -> impl Iterator<Item = (&String, &BTreeMap<String, (usize, String)>)> {
        self.by_skeleton
            .iter()
            .filter(|(_, forms)| forms.values().map(|(n, _)| *n).sum::<usize>() >= MIN_OCCURRENCES)
    }

    /// One word written with nikud in one sefer and bare in another.
    ///
    /// This is the transformation everything else rests on, and the corpus
    /// proves it is needed: Berakhot ships fully menukad and Mishnah Berurah has
    /// no nikud at all, so the same word is two different strings depending on
    /// which sefer you are reading.
    fn mark_pairs(&self) -> Vec<Row> {
        let mut rows = Vec::new();
        for (_, forms) in self.frequent() {
            let marked = forms.iter().find(|(f, _)| f.chars().any(is_mark));
            let bare = forms
                .iter()
                .find(|(f, _)| !f.chars().any(is_mark) && !f.chars().any(is_quote_mark));
            if let (Some((m, (_, m_from))), Some((b, (_, b_from)))) = (marked, bare) {
                rows.push(Row {
                    kind: "nikud",
                    left: m.clone(),
                    right: b.clone(),
                    left_from: m_from.clone(),
                    right_from: b_from.clone(),
                });
            }
            if rows.len() >= MAX_ROWS_PER_KIND {
                break;
            }
        }
        rows
    }

    /// One abbreviation written with `U+05F4` in one sefer and an ASCII quote in
    /// another — the fold that looks done and is not.
    fn quote_mark_pairs(&self) -> Vec<Row> {
        let mut rows = Vec::new();
        for (_, forms) in self.frequent() {
            let with_quotes: Vec<_> = forms
                .iter()
                .filter(|(f, _)| f.chars().any(is_quote_mark))
                .collect();
            // Two spellings of one word whose quote characters differ.
            //
            // A shared skeleton is not enough: `כְּמֹשֶׁה'` and `כמש"ה` have the
            // same letters and are not the same string at all — one is a word
            // with a geresh, the other an abbreviation whose gershayim sits
            // somewhere else. The pair only asserts something about folding if
            // the marks are in the *same places* and differ only in which
            // character was used to write them.
            for (i, (a, (_, a_from))) in with_quotes.iter().enumerate() {
                for (b, (_, b_from)) in with_quotes.iter().skip(i + 1) {
                    if quote_signature(a) != quote_signature(b) {
                        continue;
                    }
                    let a_marks: Vec<char> = a.chars().filter(|c| is_quote_mark(*c)).collect();
                    let b_marks: Vec<char> = b.chars().filter(|c| is_quote_mark(*c)).collect();
                    // A geresh and a gershayim are different marks, not two
                    // spellings of one — `שלשים'` and `שלשים"` are not the same
                    // string and nothing should make them so. Only pair forms
                    // whose marks agree in kind and differ in character.
                    let same_kinds = a_marks.len() == b_marks.len()
                        && a_marks
                            .iter()
                            .zip(&b_marks)
                            .all(|(x, y)| is_gershayim(*x) == is_gershayim(*y));
                    if same_kinds && a_marks != b_marks {
                        rows.push(Row {
                            kind: "gershayim",
                            left: (*a).clone(),
                            right: (*b).clone(),
                            left_from: a_from.clone(),
                            right_from: b_from.clone(),
                        });
                    }
                }
            }
            if rows.len() >= MAX_ROWS_PER_KIND {
                break;
            }
        }
        rows.truncate(MAX_ROWS_PER_KIND);
        rows
    }

    /// A word and the same word carrying a prefix, both real corpus vocabulary.
    fn prefix_pairs(&self) -> Vec<Row> {
        const PREFIXES: [char; 8] = ['ו', 'ה', 'ב', 'כ', 'ל', 'מ', 'ש', 'ד'];
        let mut rows = Vec::new();
        for (skeleton, forms) in self.frequent() {
            let mut chars = skeleton.chars();
            let Some(first) = chars.next() else { continue };
            if !PREFIXES.contains(&first) {
                continue;
            }
            let stem: String = chars.collect();
            if stem.chars().count() < 3 {
                continue;
            }
            // The stem has to be a word in its own right, in the corpus.
            let Some(stem_forms) = self.by_skeleton.get(&stem) else {
                continue;
            };
            if stem_forms.values().map(|(n, _)| *n).sum::<usize>() < MIN_OCCURRENCES {
                continue;
            }
            let (Some((long, long_from)), Some((short, short_from))) =
                (plain_form(forms), plain_form(stem_forms))
            else {
                continue;
            };
            rows.push(Row {
                kind: "prefix",
                left: long.clone(),
                right: short.clone(),
                left_from: long_from.clone(),
                right_from: short_from.clone(),
            });
            if rows.len() >= MAX_ROWS_PER_KIND {
                break;
            }
        }
        rows
    }

    /// Two spellings of one word differing only by an internal `ו` or `י`, both
    /// real corpus vocabulary — ktiv male against ktiv chaser, as the seforim
    /// actually disagree about it.
    fn ktiv_pairs(&self) -> Vec<Row> {
        let mut rows = Vec::new();
        for (skeleton, forms) in self.frequent() {
            let letters: Vec<char> = skeleton.chars().collect();
            if letters.len() < 4 {
                continue;
            }
            for i in 1..letters.len() - 1 {
                if letters[i] != 'ו' && letters[i] != 'י' {
                    continue;
                }
                let mut shorter = letters.clone();
                shorter.remove(i);
                let shorter: String = shorter.into_iter().collect();
                let Some(other) = self.by_skeleton.get(&shorter) else {
                    continue;
                };
                if other.values().map(|(n, _)| *n).sum::<usize>() < MIN_OCCURRENCES {
                    continue;
                }
                // An abbreviation is not a ktiv variant. `ואל"כ` shares a
                // skeleton with `ואילך` and has nothing to do with it — its ו
                // is not a mater lectionis, it is the first letter of a word
                // the gershayim stands in for.
                let (Some((male, male_from)), Some((chaser, chaser_from))) =
                    (plain_form(forms), plain_form(other))
                else {
                    continue;
                };
                rows.push(Row {
                    kind: "ktiv",
                    left: male.clone(),
                    right: chaser.clone(),
                    left_from: male_from.clone(),
                    right_from: chaser_from.clone(),
                });
                break;
            }
            if rows.len() >= MAX_ROWS_PER_KIND {
                break;
            }
        }
        rows
    }
}

/// Abbreviations from the shipped table that the seforim actually use.
///
/// This is the one place the harvester touches `girsa_hebrew`, and it takes
/// only the *table* — the data, not the transformation under test. The check
/// runs the other way from the rest of the file: the corpus is the authority,
/// and the question is whether a hand-written table entry is real. An entry
/// nobody writes is a guess about Hebrew that never has to face evidence, and a
/// table full of those is how a normalizer starts producing expansions that no
/// sefer contains.
impl Vocabulary {
    fn attested_abbreviations(&self) -> Vec<Row> {
        let mut rows = Vec::new();
        for (short, longs) in girsa_hebrew::ABBREVIATIONS.entries() {
            let Some(short_from) = self.attested(short) else {
                continue;
            };
            for long in *longs {
                let Some(long_from) = self.attested(long) else {
                    continue;
                };
                rows.push(Row {
                    kind: "abbrev",
                    left: (*short).to_string(),
                    right: (*long).to_string(),
                    left_from: short_from.clone(),
                    right_from: long_from,
                });
            }
        }
        rows
    }

    /// One sefer that uses this term, if any does. A multi-word expansion
    /// counts as used when every word of it appears.
    fn attested(&self, term: &str) -> Option<String> {
        let mut where_seen = None;
        for word in term.split_whitespace() {
            let forms = self.by_skeleton.get(&skeleton_of(word))?;
            let (_, (_, from)) = forms.iter().next()?;
            where_seen.get_or_insert_with(|| from.clone());
        }
        where_seen
    }
}

/// The first surface form that is a word rather than an abbreviation, with the
/// sefer it came from.
fn plain_form(forms: &BTreeMap<String, (usize, String)>) -> Option<(String, String)> {
    forms
        .iter()
        .find(|(f, _)| !f.chars().any(is_quote_mark))
        .map(|(f, (_, from))| (f.clone(), from.clone()))
}

// --- the harvester's own character rules, written independently -------------
//
// Deliberately not `girsa_hebrew`'s. If the fixture were grouped by the
// function under test, a regression in that function would regroup the fixture
// to agree with itself and every row would still pass.

fn is_mark(c: char) -> bool {
    matches!(c, '\u{0591}'..='\u{05BD}' | '\u{05BF}' | '\u{05C1}'..='\u{05C2}' | '\u{05C4}'..='\u{05C5}' | '\u{05C7}')
}

/// Whether a quote mark is a double one — gershayim rather than geresh.
fn is_gershayim(c: char) -> bool {
    matches!(c, '\u{05F4}' | '"' | '\u{201C}' | '\u{201D}')
}

fn is_quote_mark(c: char) -> bool {
    matches!(
        c,
        '\u{05F3}' | '\u{05F4}' | '\'' | '"' | '\u{2018}' | '\u{2019}' | '\u{201C}' | '\u{201D}'
    )
}

fn is_letter(c: char) -> bool {
    ('\u{05D0}'..='\u{05EA}').contains(&c)
}

/// The word with its letters folded and every quote mark replaced by one
/// placeholder — so two spellings that differ *only* in which quote character
/// was typed have the same signature, and two different words do not.
fn quote_signature(word: &str) -> String {
    word.chars()
        .filter(|c| !is_mark(*c))
        .map(|c| if is_quote_mark(c) { '\u{00A7}' } else { c })
        .map(fold_final)
        .collect()
}

fn fold_final(c: char) -> char {
    match c {
        'ך' => 'כ',
        'ם' => 'מ',
        'ן' => 'נ',
        'ף' => 'פ',
        'ץ' => 'צ',
        other => other,
    }
}

/// Hebrew letters only, final forms folded. Nothing else.
fn skeleton_of(word: &str) -> String {
    word.chars()
        .filter(|c| is_letter(*c))
        .map(fold_final)
        .collect()
}

/// Drop the punctuation around a word, keeping the quote marks that belong to
/// it.
///
/// A gershayim inside a word (`שו"ע`) and a geresh at the end of one (`גמ׳`) are
/// part of the word. A quote mark at the *front* is an opening quotation mark
/// around a phrase — Berakhot writes `״עַד חֲצוֹת״` — so that one goes.
fn trim_edges(raw: &str) -> &str {
    raw.trim_matches(|c: char| !is_letter(c) && !is_mark(c) && !is_quote_mark(c))
        .trim_start_matches(is_quote_mark)
}

fn collect_files(root: &Path) -> std::io::Result<Vec<PathBuf>> {
    let mut out = Vec::new();
    let mut stack = vec![root.to_path_buf()];
    while let Some(dir) = stack.pop() {
        let Ok(entries) = fs::read_dir(&dir) else {
            continue;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                stack.push(path);
            } else if path.extension().is_some_and(|e| e == "txt") {
                out.push(path);
            }
        }
    }
    out.sort();
    Ok(out)
}
